"use client";
import Link from "next/link";
import { useCallback, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { strategyRegistry } from "@/strategies/registry";

type Job = { runId: string; strategyId?: string; config?: { startDate?: string; endDate?: string }; status: string; progress?: number; currentStep?: string; errorCode?: string | null; error?: string | null; startedAt?: string | null };
export default function ProcessingClient({ runId, initial, inlineEnabled }: { runId: string; initial: Record<string, unknown>; inlineEnabled: boolean }) {
  const router = useRouter(); const [job, setJob] = useState<Job>(initial as Job); const [networkError, setNetworkError] = useState(""); const busy = useRef(false); const inlineStarted = useRef(false); const stopped = useRef(false);
  const poll = useCallback(async () => { if (busy.current || stopped.current) return; busy.current = true; try { const res = await fetch(`/api/backtest/jobs/${runId}`, { cache: "no-store" }); if (res.status === 404) { stopped.current = true; setNetworkError("Job Not Found"); return; } const data = await res.json(); setJob(data); setNetworkError(""); if (data.status === "COMPLETED") { stopped.current = true; router.replace(`/results/${runId}`); } else if (data.status === "FAILED") stopped.current = true; } catch { setNetworkError("Status belum dapat dimuat. Akan mencoba lagi otomatis."); } finally { busy.current = false; } }, [router, runId]);
  useEffect(() => { let cancelled = false; const triggerInline = async () => { if (!inlineEnabled || inlineStarted.current || job.status !== "QUEUED") return; inlineStarted.current = true; try { await fetch(`/api/backtest/jobs/${runId}/process`, { method: "POST" }); } catch { /* polling reports the final state */ } if (!cancelled) await poll(); }; triggerInline(); const id = window.setInterval(poll, 2000); return () => { cancelled = true; window.clearInterval(id); }; }, [inlineEnabled, job.status, poll, runId]);
  const strategy = strategyRegistry.find((x) => x.id === job.strategyId); const progress = Math.max(0, Math.min(100, Number(job.progress ?? 0)));
  async function retry() { const res = await fetch(`/api/backtest/jobs/${runId}/retry`, { method: "POST" }); if (res.ok) { stopped.current = false; setJob((x) => ({ ...x, status: "QUEUED", progress: 0, error: null, errorCode: null })); inlineStarted.current = false; } }
  if (job.status === "NOT_FOUND") return <div className="mx-auto max-w-2xl space-y-4"><h2 className="text-2xl font-bold">Job Not Found</h2><p className="text-slate-400">Backtest {runId} tidak ditemukan.</p><Link className="text-amber-300 hover:underline" href="/results">Back to Results</Link></div>;
  return <div className="mx-auto max-w-2xl space-y-6"><div><h2 className="text-2xl font-bold">Backtest sedang diproses</h2><p className="mt-1 text-sm text-slate-400">Halaman ini boleh tetap dibuka. Status diperbarui otomatis.</p></div><div className="rounded-lg border border-slate-800 bg-slate-900 p-5"><div className="grid gap-3 text-sm sm:grid-cols-2"><div><span className="text-slate-400">Backtest ID</span><div className="font-mono text-amber-300">{runId}</div></div><div><span className="text-slate-400">Strategy</span><div>{strategy?.name ?? job.strategyId ?? "-"}</div></div><div><span className="text-slate-400">Periode</span><div>{job.config?.startDate ?? "-"} → {job.config?.endDate ?? "-"}</div></div><div><span className="text-slate-400">Status</span><div className="font-semibold">{job.status}</div></div></div><div className="mt-6"><div className="mb-2 flex justify-between text-sm"><span>{job.currentStep ?? "Waiting for worker"}</span><span>{progress}%</span></div><div className="h-3 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-amber-500 transition-all" style={{ width: `${progress}%` }} /></div></div>{job.startedAt && <p className="mt-4 text-xs text-slate-500">Mulai: {new Date(job.startedAt).toLocaleString()}</p>}{networkError && <p className="mt-4 rounded border border-amber-800 bg-amber-950/40 p-3 text-sm text-amber-300">{networkError}</p>}{job.status === "FAILED" && <div className="mt-4 rounded border border-red-800 bg-red-950/50 p-3 text-sm text-red-300"><div className="font-semibold">Backtest gagal</div><div>Error code: {job.errorCode ?? "BACKTEST_FAILED"}</div><div className="mt-1">{job.error ?? "Worker gagal memproses job."}</div><div className="mt-3 flex flex-wrap gap-2"><button className="rounded bg-amber-500 px-3 py-1.5 font-semibold text-slate-950" onClick={retry}>Retry</button><Link className="rounded border border-slate-700 px-3 py-1.5" href="/new">Back to New Backtest</Link></div></div>}<Link className="mt-5 inline-block text-sm text-slate-400 hover:text-white" href="/results">Back to Results</Link></div></div>;
}
