import { getMongoDb } from "./mongodb";
import { MongoCandleRepository } from "@/data/mongo-candle-repository";
import { BreakoutEngine } from "@/backtest/engine";
import { computeMetrics } from "@/backtest/metrics";
import { pipsToPrice, BREAKOUT_METHOD_NAME, CALCULATION_VERSION, PIP_SIZE, PIP_VALUE_PER_LOT_USD } from "@/backtest/methods";
import { qualificationReason, scoreBatchResults, type BatchCombination, type BatchScoreRow } from "./batch-grid";
import { tradeUpsertOperations, equityUpsertOperations, validateEquity, validateTrades } from "./cloud-backtest-worker";
import type { BacktestRequest, BacktestTrade } from "@/backtest/types";
import type { Db } from "mongodb";
import { runTrendPullbackH1Request } from "@/strategies/xau_trend_pullback_h1/runner";
import { XAU_TREND_PULLBACK_H1_ID, XAU_TREND_PULLBACK_H1_NAME } from "@/strategies/xau_trend_pullback_h1/config";
import { BREAKOUT_H4_EMA_TREND_ID, BREAKOUT_H4_EMA_TREND_NAME, BREAKOUT_H4_EMA_TREND_WARMUP, buildH4EmaTrendFilter } from "@/strategies/breakout_h4_ema_trend";
import { BREAKOUT_H4_STOP_AFTER_1_LOSS_ID, BREAKOUT_H4_STOP_AFTER_1_LOSS_NAME, BREAKOUT_H4_STOP_AFTER_1_LOSS_RULE, createStopAfterOneDailyLoss, existingCandleTimezone, summarizeDailyLosses } from "@/strategies/breakout_h4_stop_after_1_loss";
import { DAILY_PREVIOUS_CANDLE_BREAKOUT_ID, DAILY_PREVIOUS_CANDLE_BREAKOUT_NAME, DAILY_PREVIOUS_CANDLE_BREAKOUT_ENTRY_OFFSET, DailyPreviousCandleBreakoutEngine } from "@/strategies/daily_previous_candle_breakout";

type BatchJob = { batchId: string; status: string; config: BacktestRequest & { combinations: BatchCombination[]; strategyId: string }; totalCombinations: number; completedCombinations: number; failedCombinations: number; progress: number; createdAt: Date; workerLockAt?: Date | null };
const safeError = (e: unknown) => e instanceof Error ? e.message.split("\n")[0].slice(0, 500) : "BATCH_COMBINATION_FAILED";

async function runCombination(req: BacktestRequest, combination: BatchCombination) {
  const from = new Date(`${req.startDate}T00:00:00.000Z`); const to = new Date(`${req.endDate}T23:59:59.999Z`); const repo = new MongoCandleRepository();
  if (req.strategyId === BREAKOUT_H4_EMA_TREND_ID) {
    const h4 = await repo.getCandles("XAUUSD", "H4", new Date(from.getTime() - 2400 * 3600_000), to); const m1 = await repo.getCandles("XAUUSD", "M1", from, to); if (h4.length < BREAKOUT_H4_EMA_TREND_WARMUP + 2 || !m1.length) throw new Error("INSUFFICIENT_H4_EMA_WARMUP");
    const trend = buildH4EmaTrendFilter(h4, from.getTime()); const engine = new BreakoutEngine(h4, { breakoutDistance: pipsToPrice(Number(combination.breakoutPips)), stopLossDistance: pipsToPrice(Number(combination.stopLossPips)), takeProfitDistance: pipsToPrice(Number(combination.takeProfitPips)), lot: req.lot, initialBalance: req.initialBalance, spread: 0, slippage: 0, commission: 0, session: "ALL", ambiguousHandling: "SKIP", entryFilter: trend.filter }); for (const c of m1) engine.onM1(c); engine.finish(); engine.equity[0].time = from.toISOString(); return { engine, metrics: computeMetrics(engine.trades, engine.equity, req.initialBalance), h4Count: h4.length, m1Count: m1.length, riskReward: Number(combination.takeProfitPips) / Number(combination.stopLossPips) };
  }
  if (req.strategyId === BREAKOUT_H4_STOP_AFTER_1_LOSS_ID) {
    const h4 = await repo.getCandles("XAUUSD", "H4", new Date(from.getTime() - 8 * 3600_000), to); const m1 = await repo.getCandles("XAUUSD", "M1", from, to); if (h4.length < 2 || !m1.length) throw new Error("INSUFFICIENT_CLOUD_CANDLES");
    const stop = createStopAfterOneDailyLoss(); const engine = new BreakoutEngine(h4, { breakoutDistance: pipsToPrice(Number(combination.breakoutPips)), stopLossDistance: pipsToPrice(Number(combination.stopLossPips)), takeProfitDistance: pipsToPrice(Number(combination.takeProfitPips)), lot: req.lot, initialBalance: req.initialBalance, spread: 0, slippage: 0, commission: 0, session: "ALL", ambiguousHandling: "SKIP", entryGuard: stop.canEnter, onTradeClosed: stop.onTradeClosed }); for (const c of m1) engine.onM1(c); engine.finish(); engine.equity[0].time = from.toISOString();
    return { engine, metrics: computeMetrics(engine.trades, engine.equity, req.initialBalance), h4Count: h4.length, m1Count: m1.length, riskReward: Number(combination.takeProfitPips) / Number(combination.stopLossPips), dailyStopStats: stop.stats, daily: summarizeDailyLosses(engine.trades) };
  }
  if (req.strategyId === DAILY_PREVIOUS_CANDLE_BREAKOUT_ID) {
    const daily = await repo.getCandles("XAUUSD", "D1", new Date(0), to); const m1 = await repo.getCandles("XAUUSD", "M1", from, to); if (daily.length < 2 || !m1.length) throw new Error("INSUFFICIENT_D1_M1_CANDLES");
    const engine = new DailyPreviousCandleBreakoutEngine(daily, { breakoutDistance: 0, stopLossDistance: pipsToPrice(Number(combination.stopLossPips ?? 200)), takeProfitDistance: pipsToPrice(Number(combination.takeProfitPips ?? 400)), lot: req.lot, initialBalance: req.initialBalance, spread: 0, slippage: 0, commission: 0, session: "ALL", ambiguousHandling: "SKIP", entryOffset: Number(combination.entryOffset ?? req.entryOffset ?? DAILY_PREVIOUS_CANDLE_BREAKOUT_ENTRY_OFFSET) }); for (const c of m1) engine.onM1(c); engine.finish(); engine.equity[0].time = from.toISOString(); return { engine, metrics: computeMetrics(engine.trades, engine.equity, req.initialBalance), d1Count: daily.length, m1Count: m1.length, riskReward: Number(combination.takeProfitPips ?? 400) / Number(combination.stopLossPips ?? 200), dailyStats: { noTriggerDays: engine.noTriggerDays, pendingExpiredDays: engine.pendingExpiredDays, ambiguousCandles: engine.ambiguousSignals }, dailyConfig: { entryOffset: Number(combination.entryOffset ?? req.entryOffset ?? DAILY_PREVIOUS_CANDLE_BREAKOUT_ENTRY_OFFSET), previousDailyHigh: engine.previousDailyHigh, previousDailyLow: engine.previousDailyLow, buyStop: engine.buyStop, sellStop: engine.sellStop } };
  }
  if (req.strategyId === XAU_TREND_PULLBACK_H1_ID) {
    const h1 = await repo.getCandles("XAUUSD", "H1", from, to); if (h1.length < 205) throw new Error("INSUFFICIENT_H1_WARMUP");
    const result = runTrendPullbackH1Request(req, h1); return { engine: result.engine, metrics: computeMetrics(result.engine.trades, result.engine.equity, req.initialBalance), h1Count: h1.length, riskReward: 2 };
  }
  const breakoutPips = combination.breakoutPips; const stopLossPips = combination.stopLossPips; const takeProfitPips = combination.takeProfitPips;
  if (!(breakoutPips && stopLossPips && takeProfitPips)) throw new Error("INVALID_BREAKOUT_COMBINATION");
  const h4 = await repo.getCandles("XAUUSD", "H4", new Date(from.getTime() - 8 * 3600_000), to); const m1 = await repo.getCandles("XAUUSD", "M1", from, to); if (h4.length < 2 || !m1.length) throw new Error("INSUFFICIENT_CLOUD_CANDLES");
  const engine = new BreakoutEngine(h4, { breakoutDistance: pipsToPrice(breakoutPips), stopLossDistance: pipsToPrice(stopLossPips), takeProfitDistance: pipsToPrice(takeProfitPips), lot: req.lot, initialBalance: req.initialBalance, spread: 0, slippage: 0, commission: 0, session: "ALL", ambiguousHandling: "SKIP" }); for (const candle of m1) engine.onM1(candle); engine.finish(); engine.equity[0].time = from.toISOString();
  const metrics = computeMetrics(engine.trades, engine.equity, req.initialBalance); const riskReward = takeProfitPips / stopLossPips;
  return { engine, metrics, h4Count: h4.length, m1Count: m1.length, riskReward };
}

async function saveTopDetail(db: Db, batch: { batchId: string }, row: Record<string, unknown>, rank: number, req: BacktestRequest) {
  if (row.detailRunId) return;
  const combinationId = String(row.combinationId); const breakoutPips = Number(row.breakoutPips); const stopLossPips = Number(row.stopLossPips); const takeProfitPips = Number(row.takeProfitPips);
  const result = await runCombination(req, { combinationId, breakoutPips, stopLossPips, takeProfitPips });
  const runId = `${batch.batchId}-TOP${String(rank).padStart(2, "0")}`; const executed = result.engine.trades.filter((t: BacktestTrade) => t.result !== "SKIPPED" && t.result !== "AMBIGUOUS"); const trades = validateTrades(runId, executed).documents; const equity = validateEquity(runId, result.engine.equity);
  if (trades.length) await db.collection("backtest_trades").bulkWrite(tradeUpsertOperations(trades), { ordered: false }); if (equity.length) await db.collection("backtest_equity").bulkWrite(equityUpsertOperations(equity), { ordered: false });
  const isH1 = req.strategyId === XAU_TREND_PULLBACK_H1_ID;
  const effectiveTradingStart = "effectiveTradingStart" in result.engine ? result.engine.effectiveTradingStart : undefined;
  const warmupCandlesUsed = "warmupCandlesUsed" in result.engine ? result.engine.warmupCandlesUsed : undefined;
  const isEma = req.strategyId === BREAKOUT_H4_EMA_TREND_ID;
  const isStop = req.strategyId === BREAKOUT_H4_STOP_AFTER_1_LOSS_ID;
  const isDaily = req.strategyId === DAILY_PREVIOUS_CANDLE_BREAKOUT_ID;
  const config = isH1 ? { runId, strategyId: XAU_TREND_PULLBACK_H1_ID, strategyName: XAU_TREND_PULLBACK_H1_NAME, method: XAU_TREND_PULLBACK_H1_NAME, ...req, requestedStartDate: req.startDate, effectiveTradingStart, warmupCandlesUsed, executionTimeframe: "H1", riskReward: 2, emaFastPeriod: 50, emaSlowPeriod: 200, atrPeriod: 14, warmupCandles: 204, pullbackAtrTolerance: 0.25, trendAtrSeparation: 0.5, swingLookback: 10, swingFractalRadius: 2, swingBufferAtr: 0.1, stopAtrMultiple: 1.5, confirmationBodyMin: 0.5, confirmationCloseTopFraction: 0.75, maxTradesPerDay: 2, maxLossesPerDay: 2, pipSize: PIP_SIZE, pipValuePerLotUSD: PIP_VALUE_PER_LOT_USD, calculationVersion: CALCULATION_VERSION, sourceBatchId: batch.batchId, sourceCombinationId: combinationId, rank } : { runId, strategyId: isEma ? BREAKOUT_H4_EMA_TREND_ID : "xau_h4_breakout", strategyName: isEma ? BREAKOUT_H4_EMA_TREND_NAME : BREAKOUT_METHOD_NAME, method: isEma ? BREAKOUT_H4_EMA_TREND_NAME : BREAKOUT_METHOD_NAME, ...req, breakoutPips, stopLossPips, takeProfitPips, breakoutPriceDistance: pipsToPrice(breakoutPips), stopLossPriceDistance: pipsToPrice(stopLossPips), takeProfitPriceDistance: pipsToPrice(takeProfitPips), riskReward: Number(row.riskReward), ...(isEma ? { emaFastPeriod: 50, emaSlowPeriod: 200, warmupCandles: BREAKOUT_H4_EMA_TREND_WARMUP } : {}), pipSize: PIP_SIZE, pipValuePerLotUSD: PIP_VALUE_PER_LOT_USD, calculationVersion: CALCULATION_VERSION, sourceBatchId: batch.batchId, sourceCombinationId: combinationId, rank };
  if (isStop) Object.assign(config, { strategyId: BREAKOUT_H4_STOP_AFTER_1_LOSS_ID, strategyName: BREAKOUT_H4_STOP_AFTER_1_LOSS_NAME, method: BREAKOUT_H4_STOP_AFTER_1_LOSS_NAME, dailyStopRule: BREAKOUT_H4_STOP_AFTER_1_LOSS_RULE, dailyStopTimezone: existingCandleTimezone, dailyBlockedDays: result.dailyStopStats?.blockedDays.size, dailySkippedSignals: result.dailyStopStats?.skippedSignals, worstDailyLoss: result.daily?.worstDailyLoss, consecutiveLosingDays: result.daily?.consecutiveLosingDays });
  if (isDaily) Object.assign(config, { strategyId: DAILY_PREVIOUS_CANDLE_BREAKOUT_ID, strategyName: DAILY_PREVIOUS_CANDLE_BREAKOUT_NAME, method: DAILY_PREVIOUS_CANDLE_BREAKOUT_NAME, entryOffset: result.dailyConfig?.entryOffset, previousDailyHigh: result.dailyConfig?.previousDailyHigh ?? undefined, previousDailyLow: result.dailyConfig?.previousDailyLow ?? undefined, buyStop: result.dailyConfig?.buyStop ?? undefined, sellStop: result.dailyConfig?.sellStop ?? undefined, noTriggerDays: result.dailyStats?.noTriggerDays, pendingExpiredDays: result.dailyStats?.pendingExpiredDays, dailyAmbiguousCandles: result.dailyStats?.ambiguousCandles, dailyStopTimezone: "UTC" });
  await db.collection("backtest_runs").replaceOne({ runId }, { runId, strategyId: isH1 ? XAU_TREND_PULLBACK_H1_ID : isDaily ? DAILY_PREVIOUS_CANDLE_BREAKOUT_ID : isStop ? BREAKOUT_H4_STOP_AFTER_1_LOSS_ID : isEma ? BREAKOUT_H4_EMA_TREND_ID : "xau_h4_breakout", strategyName: isH1 ? XAU_TREND_PULLBACK_H1_NAME : isDaily ? DAILY_PREVIOUS_CANDLE_BREAKOUT_NAME : isStop ? BREAKOUT_H4_STOP_AFTER_1_LOSS_NAME : isEma ? BREAKOUT_H4_EMA_TREND_NAME : BREAKOUT_METHOD_NAME, config, summary: result.metrics, calculationVersion: CALCULATION_VERSION, createdAt: new Date(), completedAt: new Date(), sourceBatchId: batch.batchId, sourceCombinationId: combinationId, rank }, { upsert: true });
  await db.collection("batch_backtest_results").updateOne({ batchId: batch.batchId, combinationId }, { $set: { detailRunId: runId, rank, status: "QUALIFIED" } });
}

export async function processOneBatch(batchId: string) {
  const db = await getMongoDb(); const jobs = db.collection<BatchJob>("batch_backtest_jobs"); const now = new Date();
  const job = await jobs.findOneAndUpdate({ batchId, status: { $in: ["QUEUED", "RUNNING"] }, $or: [{ workerLockAt: null }, { workerLockAt: { $exists: false } }, { workerLockAt: { $lt: new Date(now.getTime() - 10 * 60_000) } }] }, { $set: { status: "RUNNING", startedAt: now, workerLockAt: now, error: null, errorCode: null } }, { returnDocument: "after" });
  if (!job) return { status: "RUNNING" as const, batchId, locked: true };
  try {
    const existing = await db.collection("batch_backtest_results").find({ batchId }).toArray(); const done = new Set(existing.filter((x) => x.status === "COMPLETED" || x.status === "QUALIFIED").map((x) => x.combinationId)); const queued = existing.find((x) => x.status === "QUEUED"); const combination = queued ? job.config.combinations.find((x) => x.combinationId === queued.combinationId) : job.config.combinations.find((candidate) => !done.has(candidate.combinationId) && !existing.some((stored) => stored.combinationId === candidate.combinationId && stored.status === "FAILED"));
    if (combination) {
      const started = Date.now(); try { const result = await runCombination(job.config, combination); const m = result.metrics; const reasons = qualificationReason({ totalTrades: m.totalTrades, profitFactor: m.profitFactor ?? 0, maximumDrawdownPercent: m.maxDrawdownPercent, netProfit: m.netProfit }); await db.collection("batch_backtest_results").updateOne({ batchId, combinationId: combination.combinationId }, { $set: { batchId, combinationId: combination.combinationId, strategyId: job.config.strategyId, breakoutPips: combination.breakoutPips, stopLossPips: combination.stopLossPips, takeProfitPips: combination.takeProfitPips, riskReward: result.riskReward, lot: job.config.lot, initialBalance: job.config.initialBalance, startDate: job.config.startDate, endDate: job.config.endDate, totalTrades: m.totalTrades, wins: m.winningTrades, losses: m.losingTrades, breakEven: m.breakevenTrades, openAtEndCount: m.openAtEndTrades, winRate: m.winRate, profitFactor: m.profitFactor ?? 0, netProfit: m.netProfit, finalBalance: m.finalBalance, maximumDrawdown: m.maxDrawdown, maximumDrawdownPercent: m.maxDrawdownPercent, overallScore: 0, qualification: reasons.length ? "REJECTED" : "QUALIFIED", rejectionReason: reasons.join("; "), status: "COMPLETED", executionTimeMs: Date.now() - started, createdAt: new Date() } }, { upsert: true }); } catch (e) { await db.collection("batch_backtest_results").updateOne({ batchId, combinationId: combination.combinationId }, { $set: { batchId, combinationId: combination.combinationId, status: "FAILED", error: safeError(e), createdAt: new Date() } }, { upsert: true }); }
    }
    const results = await db.collection("batch_backtest_results").find({ batchId }).toArray(); const completed = results.filter((x) => x.status === "COMPLETED"); const failed = results.filter((x) => x.status === "FAILED"); const scored = scoreBatchResults(completed as BatchScoreRow[]); for (let i = 0; i < scored.length; i++) await db.collection("batch_backtest_results").updateOne({ batchId, combinationId: String(scored[i].combinationId) }, { $set: { overallScore: Number(scored[i].overallScore), rank: i + 1 } });
    const total = job.totalCombinations; const finished = completed.length + failed.length; if (finished >= total) { const qualified = scored.filter((x) => qualificationReason(x).length === 0); for (let i = 0; i < Math.min(5, qualified.length); i++) await saveTopDetail(db, job, qualified[i], i + 1, job.config); await jobs.updateOne({ batchId }, { $set: { status: completed.length ? "COMPLETED" : "FAILED", completedCombinations: completed.length, failedCombinations: failed.length, progress: 100, currentCombination: null, currentParameters: null, completedAt: new Date(), workerLockAt: null } }); return { status: completed.length ? "COMPLETED" as const : "FAILED" as const, batchId, progress: 100, completedCombinations: completed.length, failedCombinations: failed.length }; }
    await jobs.updateOne({ batchId }, { $set: { status: "QUEUED", completedCombinations: completed.length, failedCombinations: failed.length, progress: Math.round(finished / total * 100), currentCombination: finished + 1, currentParameters: combination, workerLockAt: null } }); return { status: "QUEUED" as const, batchId, progress: Math.round(finished / total * 100), completedCombinations: completed.length, failedCombinations: failed.length };
  } catch (e) { await jobs.updateOne({ batchId }, { $set: { status: "FAILED", errorCode: "BATCH_SYSTEM_ERROR", error: safeError(e), workerLockAt: null, completedAt: new Date() } }); return { status: "FAILED" as const, batchId, error: safeError(e) }; }
}
