import { getMongoDb } from "./mongodb";
import { MongoCandleRepository } from "@/data/mongo-candle-repository";
import { BreakoutEngine } from "@/backtest/engine";
import { computeMetrics } from "@/backtest/metrics";
import { pipsToPrice, BREAKOUT_METHOD_NAME, CALCULATION_VERSION, PIP_SIZE, PIP_VALUE_PER_LOT_USD } from "@/backtest/methods";
import { qualificationReason, scoreBatchResults, type BatchCombination, type BatchScoreRow } from "./batch-grid";
import { tradeUpsertOperations, equityUpsertOperations, validateEquity, validateTrades } from "./cloud-backtest-worker";
import type { BacktestRequest, BacktestTrade } from "@/backtest/types";
import type { Db } from "mongodb";

type BatchJob = { batchId: string; status: string; config: BacktestRequest & { combinations: BatchCombination[]; strategyId: string }; totalCombinations: number; completedCombinations: number; failedCombinations: number; progress: number; createdAt: Date; workerLockAt?: Date | null };
const safeError = (e: unknown) => e instanceof Error ? e.message.split("\n")[0].slice(0, 500) : "BATCH_COMBINATION_FAILED";

async function runCombination(req: BacktestRequest, combination: BatchCombination) {
  const from = new Date(`${req.startDate}T00:00:00.000Z`); const to = new Date(`${req.endDate}T23:59:59.999Z`); const repo = new MongoCandleRepository();
  const h4 = await repo.getCandles("XAUUSD", "H4", new Date(from.getTime() - 8 * 3600_000), to); const m1 = await repo.getCandles("XAUUSD", "M1", from, to); if (h4.length < 2 || !m1.length) throw new Error("INSUFFICIENT_CLOUD_CANDLES");
  const engine = new BreakoutEngine(h4, { breakoutDistance: pipsToPrice(combination.breakoutPips), stopLossDistance: pipsToPrice(combination.stopLossPips), takeProfitDistance: pipsToPrice(combination.takeProfitPips), lot: req.lot, initialBalance: req.initialBalance, spread: 0, slippage: 0, commission: 0, session: "ALL", ambiguousHandling: "SKIP" }); for (const candle of m1) engine.onM1(candle); engine.finish(); engine.equity[0].time = from.toISOString();
  const metrics = computeMetrics(engine.trades, engine.equity, req.initialBalance); const riskReward = combination.takeProfitPips / combination.stopLossPips;
  return { engine, metrics, h4Count: h4.length, m1Count: m1.length, riskReward };
}

async function saveTopDetail(db: Db, batch: { batchId: string }, row: Record<string, unknown>, rank: number, req: BacktestRequest) {
  if (row.detailRunId) return;
  const combinationId = String(row.combinationId); const breakoutPips = Number(row.breakoutPips); const stopLossPips = Number(row.stopLossPips); const takeProfitPips = Number(row.takeProfitPips);
  const result = await runCombination(req, { combinationId, breakoutPips, stopLossPips, takeProfitPips });
  const runId = `${batch.batchId}-TOP${String(rank).padStart(2, "0")}`; const executed = result.engine.trades.filter((t: BacktestTrade) => t.result !== "SKIPPED" && t.result !== "AMBIGUOUS"); const trades = validateTrades(runId, executed).documents; const equity = validateEquity(runId, result.engine.equity);
  if (trades.length) await db.collection("backtest_trades").bulkWrite(tradeUpsertOperations(trades), { ordered: false }); if (equity.length) await db.collection("backtest_equity").bulkWrite(equityUpsertOperations(equity), { ordered: false });
  await db.collection("backtest_runs").replaceOne({ runId }, { runId, strategyId: "xau_h4_breakout", strategyName: BREAKOUT_METHOD_NAME, config: { runId, strategyId: "xau_h4_breakout", strategyName: BREAKOUT_METHOD_NAME, method: BREAKOUT_METHOD_NAME, ...req, breakoutPips, stopLossPips, takeProfitPips, breakoutPriceDistance: pipsToPrice(breakoutPips), stopLossPriceDistance: pipsToPrice(stopLossPips), takeProfitPriceDistance: pipsToPrice(takeProfitPips), riskReward: Number(row.riskReward), pipSize: PIP_SIZE, pipValuePerLotUSD: PIP_VALUE_PER_LOT_USD, calculationVersion: CALCULATION_VERSION, sourceBatchId: batch.batchId, sourceCombinationId: combinationId, rank }, summary: result.metrics, calculationVersion: CALCULATION_VERSION, createdAt: new Date(), completedAt: new Date(), sourceBatchId: batch.batchId, sourceCombinationId: combinationId, rank }, { upsert: true });
  await db.collection("batch_backtest_results").updateOne({ batchId: batch.batchId, combinationId }, { $set: { detailRunId: runId, rank, status: "QUALIFIED" } });
}

export async function processOneBatch(batchId: string) {
  const db = await getMongoDb(); const jobs = db.collection<BatchJob>("batch_backtest_jobs"); const now = new Date();
  const job = await jobs.findOneAndUpdate({ batchId, status: { $in: ["QUEUED", "RUNNING"] }, $or: [{ workerLockAt: null }, { workerLockAt: { $exists: false } }, { workerLockAt: { $lt: new Date(now.getTime() - 10 * 60_000) } }] }, { $set: { status: "RUNNING", startedAt: now, workerLockAt: now, error: null, errorCode: null } }, { returnDocument: "after" });
  if (!job) return { status: "RUNNING" as const, batchId, locked: true };
  try {
    const existing = await db.collection("batch_backtest_results").find({ batchId }).toArray(); const done = new Set(existing.filter((x) => x.status === "COMPLETED" || x.status === "QUALIFIED").map((x) => x.combinationId)); const queued = existing.find((x) => x.status === "QUEUED"); const combination = queued ? job.config.combinations.find((x) => x.combinationId === queued.combinationId) : job.config.combinations.find((candidate) => !done.has(candidate.combinationId) && !existing.some((stored) => stored.combinationId === candidate.combinationId && stored.status === "FAILED"));
    if (combination) {
      const started = Date.now(); try { const result = await runCombination(job.config, combination); const m = result.metrics; const reasons = qualificationReason({ totalTrades: m.totalTrades, profitFactor: m.profitFactor ?? 0, maximumDrawdownPercent: m.maxDrawdownPercent, netProfit: m.netProfit }); await db.collection("batch_backtest_results").updateOne({ batchId, combinationId: combination.combinationId }, { $set: { batchId, combinationId: combination.combinationId, strategyId: job.config.strategyId, breakoutPips: combination.breakoutPips, stopLossPips: combination.stopLossPips, takeProfitPips: combination.takeProfitPips, riskReward: result.riskReward, lot: job.config.lot, initialBalance: job.config.initialBalance, startDate: job.config.startDate, endDate: job.config.endDate, totalTrades: m.totalTrades, wins: m.winningTrades, losses: m.losingTrades, breakEven: m.breakevenTrades, openAtEndCount: m.openAtEndTrades, winRate: m.winRate, profitFactor: m.profitFactor ?? 0, netProfit: m.netProfit, finalBalance: m.finalBalance, maximumDrawdown: m.maxDrawdown, maximumDrawdownPercent: m.maxDrawdownPercent, overallScore: 0, qualification: reasons.length ? "REJECTED" : "QUALIFIED", rejectionReason: reasons.join("; "), status: "COMPLETED", executionTimeMs: Date.now() - started, createdAt: new Date() } }, { upsert: true }); } catch (e) { await db.collection("batch_backtest_results").updateOne({ batchId, combinationId: combination.combinationId }, { $set: { batchId, combinationId: combination.combinationId, status: "FAILED", error: safeError(e), createdAt: new Date() } }, { upsert: true }); }
    }
    const results = await db.collection("batch_backtest_results").find({ batchId }).toArray(); const completed = results.filter((x) => x.status === "COMPLETED"); const failed = results.filter((x) => x.status === "FAILED"); const scored = scoreBatchResults(completed as BatchScoreRow[]); for (let i = 0; i < scored.length; i++) await db.collection("batch_backtest_results").updateOne({ batchId, combinationId: String(scored[i].combinationId) }, { $set: { overallScore: Number(scored[i].overallScore), rank: i + 1 } });
    const total = job.totalCombinations; const finished = completed.length + failed.length; if (finished >= total) { const qualified = scored.filter((x) => qualificationReason(x).length === 0); for (let i = 0; i < Math.min(5, qualified.length); i++) await saveTopDetail(db, job, qualified[i], i + 1, job.config); await jobs.updateOne({ batchId }, { $set: { status: completed.length ? "COMPLETED" : "FAILED", completedCombinations: completed.length, failedCombinations: failed.length, progress: 100, currentCombination: null, currentParameters: null, completedAt: new Date(), workerLockAt: null } }); return { status: completed.length ? "COMPLETED" as const : "FAILED" as const, batchId, progress: 100, completedCombinations: completed.length, failedCombinations: failed.length }; }
    await jobs.updateOne({ batchId }, { $set: { status: "QUEUED", completedCombinations: completed.length, failedCombinations: failed.length, progress: Math.round(finished / total * 100), currentCombination: finished + 1, currentParameters: combination, workerLockAt: null } }); return { status: "QUEUED" as const, batchId, progress: Math.round(finished / total * 100), completedCombinations: completed.length, failedCombinations: failed.length };
  } catch (e) { await jobs.updateOne({ batchId }, { $set: { status: "FAILED", errorCode: "BATCH_SYSTEM_ERROR", error: safeError(e), workerLockAt: null, completedAt: new Date() } }); return { status: "FAILED" as const, batchId, error: safeError(e) }; }
}
