"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { pipsToPrice } from "@/backtest/methods";
import type { BacktestTemplate } from "@/backtest/types";
import { BREAKOUT_H4_STRATEGY_ID, strategyRegistry } from "@/strategies/registry";

type Form = { name: string; startDate: string; endDate: string; breakoutPips: string; stopLossPips: string; takeProfitPips: string; lot: string; initialBalance: string };
const empty: Form = { name: "", startDate: "", endDate: "", breakoutPips: "100", stopLossPips: "200", takeProfitPips: "400", lot: "0.4", initialBalance: "10000" };
const input = "w-full rounded border border-slate-700 bg-slate-900 px-3 py-2 text-sm focus:border-amber-500 focus:outline-none";

export default function NewBacktest() {
  const router = useRouter(); const [form, setForm] = useState<Form>(empty); const [strategyId, setStrategyId] = useState(BREAKOUT_H4_STRATEGY_ID); const [templates, setTemplates] = useState<BacktestTemplate[]>([]); const [selected, setSelected] = useState(""); const [running, setRunning] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { Promise.all([fetch("/api/templates").then((r) => r.json()), fetch("/api/data/status").then((r) => r.json())]).then(([ts, status]) => { setTemplates(ts); const first = [status.h4.firstDate, status.m1.firstDate].filter(Boolean).sort().at(-1)?.slice(0, 10) || ""; const last = [status.h4.lastDate, status.m1.lastDate].filter(Boolean).sort()[0]?.slice(0, 10) || ""; setForm((f) => ({ ...f, startDate: f.startDate || (first > "2020-01-01" ? first : "2020-01-01"), endDate: f.endDate || last })); }).catch(() => setError("Tidak dapat memuat template/data.")); }, []);
  const strategy = strategyRegistry.find((s) => s.id === strategyId)!;
  const set = (key: keyof Form, value: string) => setForm((f) => ({ ...f, [key]: value }));
  const numbers = () => ({ breakoutPips: Number(form.breakoutPips), stopLossPips: Number(form.stopLossPips), takeProfitPips: Number(form.takeProfitPips), lot: Number(form.lot), initialBalance: Number(form.initialBalance) });
  function validate() { const n = numbers(); if (!form.startDate || !form.endDate || form.startDate > form.endDate) return "Tanggal mulai tidak boleh sesudah tanggal selesai."; if (Object.values(n).some((v) => !Number.isFinite(v) || v <= 0)) return "Semua nilai numerik harus lebih dari 0."; return ""; }
  function load() { const t = templates.find((x) => x.templateId === selected); if (!t) return; setForm((f) => ({ ...f, name: t.templateName, breakoutPips: String(t.config?.breakoutPips ?? t.breakoutPips), stopLossPips: String(t.config?.stopLossPips ?? t.stopLossPips), takeProfitPips: String(t.config?.takeProfitPips ?? t.takeProfitPips), lot: String(t.config?.lot ?? t.lot), initialBalance: String(t.config?.initialBalance ?? t.initialBalance) })); setMessage("Template dimuat; tanggal pilihan tetap dipertahankan."); }
  async function save() { setError(""); setMessage(""); const e = validate(); if (e) return setError(e); if (!form.name.trim()) return setError("Nama template wajib diisi."); const body = { strategyId, templateName: form.name, config: numbers(), ...numbers() }; const res = await fetch("/api/templates", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await res.json(); if (!res.ok) return setError(data.error || "Template gagal disimpan."); setTemplates((ts) => [...ts, data]); setSelected(data.templateId); setMessage("Template berhasil disimpan."); }
  async function removeTemplate() { const t = templates.find((x) => x.templateId === selected); if (!t || !confirm(`Hapus template ${t.templateName}?`)) return; const res = await fetch(`/api/templates/${t.templateId}`, { method: "DELETE" }); if (res.ok) { setTemplates((ts) => ts.filter((x) => x.templateId !== t.templateId)); setSelected(""); setMessage("Template berhasil dihapus."); } }
  async function run() { if (running) return; if (strategy.status === "DRAFT") return setError("Aturan XAU Trend Pullback H1 belum lengkap dan belum dapat dijalankan."); setError(""); const e = validate(); if (e) return setError(e); setRunning(true); try { const res = await fetch("/api/backtest/run", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ strategyId, startDate: form.startDate, endDate: form.endDate, ...numbers() }) }); const data = await res.json(); if (!res.ok) { setError(data.error || "Backtest gagal."); setRunning(false); return; } router.push(data.processingUrl || `/backtests/${data.runId}/processing`); } catch { setError("Tidak dapat membuat job backtest."); setRunning(false); } }
  const n = numbers(); const rr = n.stopLossPips > 0 ? n.takeProfitPips / n.stopLossPips : 0;
  return <div className="max-w-3xl space-y-6"><h2 className="text-2xl font-bold">New Backtest</h2><label className="block text-sm"><span className="mb-1 block text-slate-400">Strategy</span><select className={input} value={strategyId} onChange={(e) => { setStrategyId(e.target.value); setSelected(""); setMessage(""); setError(""); }}>{strategyRegistry.map((s) => <option key={s.id} value={s.id}>{s.name}{s.status === "DRAFT" ? " · DRAFT" : ""}</option>)}</select></label><p className="text-sm text-slate-400">{strategy.description} · Signal {strategy.signalTimeframe} · Execution {strategy.executionTimeframe ?? "-"}</p>
    {strategy.status === "DRAFT" && <div className="rounded-lg border border-amber-700 bg-amber-950/40 p-4 text-sm"><h3 className="font-semibold text-amber-300">XAU Trend Pullback H1 · DRAFT</h3><p className="mt-2">Aturan trend, pullback, entry, Stop Loss, dan Take Profit belum ditentukan.</p><ul className="mt-2 list-disc pl-5 text-slate-300"><li>Definisi trend</li><li>Definisi pullback</li><li>Entry Buy dan Sell</li><li>Stop Loss dan Take Profit</li><li>Timeframe eksekusi</li><li>Jam trading</li><li>Maksimal posisi</li></ul><p className="mt-3 text-amber-300">Aturan XAU Trend Pullback H1 belum lengkap dan belum dapat dijalankan.</p></div>}
    <div className="grid gap-4 md:grid-cols-2"><label className="text-sm md:col-span-2"><span className="mb-1 block text-slate-400">Nama template / konfigurasi</span><input className={input} value={form.name} onChange={(e) => set("name", e.target.value)} placeholder="Breakout RR 1:2" /></label>{(["startDate", "endDate"] as const).map((key) => <label key={key} className="text-sm"><span className="mb-1 block text-slate-400">{key === "startDate" ? "Tanggal mulai" : "Tanggal selesai"}</span><input type="date" className={input} value={form[key]} onChange={(e) => set(key, e.target.value)} /></label>)}{(["breakoutPips", "stopLossPips", "takeProfitPips", "lot", "initialBalance"] as const).map((key) => <label key={key} className="text-sm"><span className="mb-1 block text-slate-400">{key === "breakoutPips" ? "Breakout Distance (pip)" : key === "stopLossPips" ? "Stop Loss (pip)" : key === "takeProfitPips" ? "Take Profit (pip)" : key === "initialBalance" ? "Initial Balance" : "Lot"}</span><input type="number" min="0.01" step="0.01" className={input} value={form[key]} onChange={(e) => set(key, e.target.value)} /></label>)}</div>
    <div className="rounded-lg border border-slate-800 bg-slate-900 p-4 text-sm"><h3 className="font-semibold text-amber-400">Konversi dan Risk Reward</h3><div className="mt-3 grid gap-2 sm:grid-cols-3"><div>Breakout: <b>{n.breakoutPips} pip = {pipsToPrice(n.breakoutPips).toFixed(2)} harga</b></div><div>SL: <b>{n.stopLossPips} pip = {pipsToPrice(n.stopLossPips).toFixed(2)} harga</b></div><div>TP: <b>{n.takeProfitPips} pip = {pipsToPrice(n.takeProfitPips).toFixed(2)} harga</b></div></div><p className="mt-3 text-amber-300">RR = {rr ? `1:${rr.toFixed(2)}` : "-"}</p></div>
    <div className="flex flex-wrap items-end gap-2 rounded-lg border border-slate-800 bg-slate-900 p-4"><label className="min-w-64 flex-1 text-sm"><span className="mb-1 block text-slate-400">Pilih Template</span><select disabled={strategy.status === "DRAFT"} className={input} value={selected} onChange={(e) => setSelected(e.target.value)}><option value="">-- pilih --</option>{templates.filter((t) => (t.strategyId ?? BREAKOUT_H4_STRATEGY_ID) === strategyId).map((t) => <option key={t.templateId} value={t.templateId}>{t.templateName}</option>)}</select></label><button disabled={strategy.status === "DRAFT"} onClick={load} className="rounded border border-slate-700 px-3 py-2 text-sm disabled:opacity-40">Load Template</button><button disabled={strategy.status === "DRAFT"} onClick={save} className="rounded border border-amber-600 px-3 py-2 text-sm text-amber-300 disabled:opacity-40">Save Template</button><button disabled={strategy.status === "DRAFT"} onClick={removeTemplate} className="rounded border border-red-800 px-3 py-2 text-sm text-red-300 disabled:opacity-40">Delete Template</button></div>
    {message && <p className="text-sm text-emerald-400">{message}</p>}{error && <p className="rounded border border-red-800 bg-red-950 p-3 text-sm text-red-300">{error}</p>}<button onClick={run} disabled={running || strategy.status === "DRAFT"} className="rounded bg-amber-500 px-6 py-2 font-semibold text-slate-950 disabled:cursor-not-allowed disabled:opacity-50">{running ? "Running… (periode terpilih sedang diproses)" : "Run Backtest"}</button>
  </div>;
}
