"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { pipsToPrice } from "@/backtest/methods";
import type { BacktestTemplate } from "@/backtest/types";
import { BREAKOUT_H4_STRATEGY_ID, strategyRegistry } from "@/strategies/registry";
import { XAU_TREND_PULLBACK_H1_ID } from "@/strategies/xau_trend_pullback_h1/config";
import { DAILY_PREVIOUS_CANDLE_BREAKOUT_ID } from "@/strategies/daily_previous_candle_breakout";

type Form = { name: string; startDate: string; endDate: string; breakoutPips: string; stopLossPips: string; takeProfitPips: string; lot: string; initialBalance: string };
const empty: Form = { name: "", startDate: "", endDate: "", breakoutPips: "100", stopLossPips: "200", takeProfitPips: "400", lot: "0.35", initialBalance: "10000" };
const input = "w-full rounded border border-slate-700 bg-slate-900 px-3 py-2 text-sm focus:border-amber-500 focus:outline-none";

export default function NewBacktest() {
  const router = useRouter(); const [form, setForm] = useState<Form>(empty); const [strategyId, setStrategyId] = useState(BREAKOUT_H4_STRATEGY_ID); const [templates, setTemplates] = useState<BacktestTemplate[]>([]); const [selected, setSelected] = useState(""); const [running, setRunning] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const isH1 = strategyId === XAU_TREND_PULLBACK_H1_ID; const isDaily = strategyId === DAILY_PREVIOUS_CANDLE_BREAKOUT_ID; const strategy = strategyRegistry.find((s) => s.id === strategyId)!;
  useEffect(() => { Promise.all([fetch("/api/templates").then((r) => r.json()), fetch("/api/data/status").then((r) => r.json())]).then(([ts, status]) => { setTemplates(ts); const source = isDaily ? status.d1 : isH1 ? status.h1 : status.h4; const first = source?.firstDate?.slice(0, 10) || ""; const last = source?.lastDate?.slice(0, 10) || ""; setForm((f) => ({ ...f, startDate: f.startDate || first, endDate: f.endDate || last })); }).catch(() => setError("Tidak dapat memuat template/data.")); }, [isH1, isDaily]);
  const set = (key: keyof Form, value: string) => setForm((f) => ({ ...f, [key]: value }));
  const n = { breakoutPips: Number(form.breakoutPips), entryOffset: Number(form.breakoutPips), stopLossPips: Number(form.stopLossPips), takeProfitPips: Number(form.takeProfitPips), lot: Number(form.lot), initialBalance: Number(form.initialBalance) };
  function validate() { if (!form.startDate || !form.endDate || form.startDate > form.endDate) return "Tanggal mulai tidak boleh sesudah tanggal selesai."; const values = isH1 ? [n.lot, n.initialBalance] : isDaily ? [n.entryOffset, n.stopLossPips, n.takeProfitPips, n.lot, n.initialBalance] : [n.breakoutPips, n.stopLossPips, n.takeProfitPips, n.lot, n.initialBalance]; return values.some((v) => !Number.isFinite(v) || v <= 0) ? "Semua nilai numerik harus lebih dari 0." : ""; }
  function load() { const t = templates.find((x) => x.templateId === selected); if (!t) return; setForm((f) => ({ ...f, name: t.templateName, breakoutPips: String(t.config?.breakoutPips ?? t.breakoutPips), stopLossPips: String(t.config?.stopLossPips ?? t.stopLossPips), takeProfitPips: String(t.config?.takeProfitPips ?? t.takeProfitPips), lot: String(t.config?.lot ?? t.lot), initialBalance: String(t.config?.initialBalance ?? t.initialBalance) })); }
  async function run() { if (running) return; const validation = validate(); if (validation) return setError(validation); setRunning(true); setError(""); try { const body = isH1 ? { strategyId, startDate: form.startDate, endDate: form.endDate, lot: n.lot, initialBalance: n.initialBalance } : isDaily ? { strategyId, startDate: form.startDate, endDate: form.endDate, entryOffset: n.entryOffset, stopLossPips: n.stopLossPips, takeProfitPips: n.takeProfitPips, lot: n.lot, initialBalance: n.initialBalance } : { strategyId, startDate: form.startDate, endDate: form.endDate, ...n }; const res = await fetch("/api/backtest/run", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await res.json(); if (!res.ok) { setError(data.error || "Backtest gagal."); setRunning(false); return; } router.push(data.processingUrl || `/backtests/${data.runId}/processing`); } catch { setError("Tidak dapat membuat job backtest."); setRunning(false); } }
  const rr = n.stopLossPips > 0 ? n.takeProfitPips / n.stopLossPips : 0;
  return <div className="max-w-3xl space-y-6"><h2 className="text-2xl font-bold">New Backtest</h2><label className="block text-sm"><span className="mb-1 block text-slate-400">Strategy</span><select className={input} value={strategyId} onChange={(e) => { setStrategyId(e.target.value); setSelected(""); setMessage(""); setError(""); }}>{strategyRegistry.map((s) => <option key={s.id} value={s.id}>{s.name}{s.status === "DRAFT" ? " · DRAFT" : ""}</option>)}</select></label><p className="text-sm text-slate-400">{strategy.description} · Signal {strategy.signalTimeframe} · Entry {strategy.executionTimeframe ?? "-"}</p>
    <div className="grid gap-4 md:grid-cols-2"><label className="text-sm md:col-span-2"><span className="mb-1 block text-slate-400">Nama template / konfigurasi</span><input className={input} value={form.name} onChange={(e) => set("name", e.target.value)} placeholder={isH1 ? "XAU Trend Pullback H1" : isDaily ? "Daily Previous Candle Breakout" : "Breakout RR 1:2"} /></label>{(["startDate", "endDate"] as const).map((key) => <label key={key} className="text-sm"><span className="mb-1 block text-slate-400">{key === "startDate" ? "Tanggal mulai" : "Tanggal selesai"}</span><input type="date" className={input} value={form[key]} onChange={(e) => set(key, e.target.value)} /></label>)}{(isH1 ? (["lot", "initialBalance"] as const) : isDaily ? (["breakoutPips", "stopLossPips", "takeProfitPips", "lot", "initialBalance"] as const) : (["breakoutPips", "stopLossPips", "takeProfitPips", "lot", "initialBalance"] as const)).map((key) => <label key={key} className="text-sm"><span className="mb-1 block text-slate-400"><>{key === "breakoutPips" ? (isDaily ? "Entry Offset (harga absolut)" : "Breakout Distance (pip)") : key === "stopLossPips" ? "Stop Loss (pip)" : key === "takeProfitPips" ? "Take Profit (pip)" : key === "initialBalance" ? "Initial Balance" : "Lot"}</></span><input type="number" min="0.01" step="0.01" className={input} value={form[key]} onChange={(e) => set(key, e.target.value)} /></label>)}</div>
    {isH1 ? <div className="rounded-lg border border-slate-800 bg-slate-900 p-4 text-sm"><h3 className="font-semibold text-amber-400">Canonical H1 Parameters</h3><div className="mt-3 grid gap-2 sm:grid-cols-4"><div>EMA <b>50</b></div><div>EMA <b>200</b></div><div>ATR <b>14</b></div><div>RR <b>1:2</b></div></div><p className="mt-2 text-slate-400">Entry dan manajemen posisi memakai open/high/low/close H1. M1, EMA20, fixed-pip buffer, dan fixed-pip SL/TP tidak digunakan.</p></div> : isDaily ? <div className="rounded-lg border border-slate-800 bg-slate-900 p-4 text-sm"><h3 className="font-semibold text-amber-400">Daily Closed Candle Levels</h3><div className="mt-3 grid gap-2 sm:grid-cols-3"><div>Entry Offset: <b>{n.entryOffset.toFixed(2)} harga</b></div><div>SL: <b>{n.stopLossPips} pip</b></div><div>TP: <b>{n.takeProfitPips} pip</b></div></div><p className="mt-3 text-slate-400">Level dihitung dari High/Low Daily closed sebelumnya; entry dan manajemen posisi memakai M1.</p></div> : <div className="rounded-lg border border-slate-800 bg-slate-900 p-4 text-sm"><h3 className="font-semibold text-amber-400">Konversi dan Risk Reward</h3><div className="mt-3 grid gap-2 sm:grid-cols-3"><div>Breakout: <b>{n.breakoutPips} pip = {pipsToPrice(n.breakoutPips).toFixed(2)} harga</b></div><div>SL: <b>{n.stopLossPips} pip = {pipsToPrice(n.stopLossPips).toFixed(2)} harga</b></div><div>TP: <b>{n.takeProfitPips} pip = {pipsToPrice(n.takeProfitPips).toFixed(2)} harga</b></div></div><p className="mt-3 text-amber-300">RR = {rr ? `1:${rr.toFixed(2)}` : "-"}</p></div>}
    <div className="flex flex-wrap items-end gap-2 rounded-lg border border-slate-800 bg-slate-900 p-4"><label className="min-w-64 flex-1 text-sm"><span className="mb-1 block text-slate-400">Pilih Template</span><select disabled={isH1} className={input} value={selected} onChange={(e) => setSelected(e.target.value)}><option value="">-- pilih --</option>{templates.filter((t) => (t.strategyId ?? BREAKOUT_H4_STRATEGY_ID) === strategyId).map((t) => <option key={t.templateId} value={t.templateId}>{t.templateName}</option>)}</select></label><button disabled={isH1} onClick={load} className="rounded border border-slate-700 px-3 py-2 text-sm disabled:opacity-40">Load Template</button></div>
    {message && <p className="text-sm text-emerald-400">{message}</p>}{error && <p className="rounded border border-red-800 bg-red-950 p-3 text-sm text-red-300">{error}</p>}<button onClick={run} disabled={running || strategy.status === "DRAFT"} className="rounded bg-amber-500 px-6 py-2 font-semibold text-slate-950 disabled:cursor-not-allowed disabled:opacity-50">{running ? "Running…" : "Run Backtest"}</button>
  </div>;
}
