"use client";
import { useEffect, useState } from "react";
import type { RunSummary, StoredConfig } from "@/backtest/types";
import { isLegacyRun } from "@/backtest/types";
type Sort = "winRate" | "profitFactor" | "netProfit" | "drawdown" | "trades";
const cfg = (r: RunSummary) => r.config as Partial<StoredConfig>;
export default function ComparePage() { const [runs, setRuns] = useState<RunSummary[]>([]); const [sort, setSort] = useState<Sort>("winRate"); const [selected, setSelected] = useState<string[]>([]);
  useEffect(() => { fetch("/api/backtest/results").then((r) => r.json()).then((data: RunSummary[]) => setRuns(data.filter((r) => r.status === "COMPLETED" && r.metrics && !isLegacyRun(r)))).catch(() => setRuns([])); }, []);
  const sorted = [...runs].sort((a, b) => { const av = a.metrics!; const bv = b.metrics!; if (sort === "drawdown") return av.maxDrawdownPercent - bv.maxDrawdownPercent; const get = (m: typeof av) => sort === "winRate" ? m.winRate : sort === "profitFactor" ? (m.profitFactor ?? -Infinity) : sort === "netProfit" ? m.netProfit : m.totalTrades; return get(bv) - get(av); }); const shown = selected.length ? sorted.filter((r) => selected.includes(r.runId)) : sorted;
  return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-bold">Compare Results</h2><p className="text-sm text-slate-400">Hasil strategi dibandingkan berdasarkan strategyId.</p></div><label className="text-sm text-slate-400">Sorting <select className="ml-2 rounded border border-slate-700 bg-slate-900 px-2 py-1 text-white" value={sort} onChange={(e) => setSort(e.target.value as Sort)}><option value="winRate">Win Rate tertinggi</option><option value="profitFactor">Profit Factor tertinggi</option><option value="netProfit">Net Profit tertinggi</option><option value="drawdown">Drawdown terendah</option><option value="trades">Total Trade terbanyak</option></select></label></div><div className="flex flex-wrap gap-2">{sorted.map((r) => <button key={r.runId} onClick={() => setSelected((s) => s.includes(r.runId) ? s.filter((x) => x !== r.runId) : [...s, r.runId])} className={`rounded border px-3 py-1.5 text-sm ${selected.includes(r.runId) ? "border-amber-500 bg-amber-950 text-amber-300" : "border-slate-700"}`}>{r.runId}</button>)}</div>{shown.length ? <div className="overflow-x-auto rounded-lg border border-slate-800"><table className="w-full min-w-[1300px] text-sm"><thead className="bg-slate-900 text-left text-slate-400"><tr>{["Run","Strategy","Period","Parameters","Lot","Trades","Win","Loss","Win Rate","Profit Factor","Net Profit","Max DD","Max DD %"].map((x) => <th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{shown.map((r) => { const c = cfg(r); const m = r.metrics!; const h1 = c.strategyId === "xau_trend_pullback_h1"; const daily = c.strategyId === "daily_previous_candle_breakout"; return <tr key={r.runId} className="border-t border-slate-800"><td className="p-3 font-semibold text-amber-300">{r.runId}</td><td className="p-3">{c.strategyName ?? c.method ?? "Breakout H4"}</td><td className="p-3">{c.startDate} → {c.endDate}</td><td className="p-3">{h1 ? "EMA50 / EMA200 / ATR14 · RR 1:2" : daily ? `D1 Previous High/Low · Offset ${c.entryOffset ?? "-"} · SL ${c.stopLossPips ?? "-"} · TP ${c.takeProfitPips ?? "-"}` : `Breakout ${c.breakoutPips ?? "-"} · SL ${c.stopLossPips ?? "-"} · TP ${c.takeProfitPips ?? "-"} · RR 1:${c.riskReward ?? "-"}`}</td><td className="p-3">{c.lot}</td><td className="p-3">{m.totalTrades}</td><td className="p-3">{m.winningTrades}</td><td className="p-3">{m.losingTrades}</td><td className="p-3">{m.winRate.toFixed(2)}%</td><td className="p-3">{m.profitFactor ?? "-"}</td><td className="p-3">{m.netProfit.toFixed(2)}</td><td className="p-3">{m.maxDrawdown.toFixed(2)}</td><td className="p-3">{m.maxDrawdownPercent.toFixed(2)}%</td></tr>; })}</tbody></table></div> : <p className="text-slate-400">Belum ada backtest READY yang dapat dibandingkan.</p>}</div>;
}
