import type { BacktestTrade } from "@/backtest/types";
import type { PropFirmProgram } from "@/config/prop-firm-programs";
export type SimulationResult = { startDate: string; step1: "PASS" | "FAIL"; step2: "PASS" | "FAIL"; step1Days: number | null; step2Days: number | null; profitableDays: number; finalBalance: number; netProfit: number; worstDailyLoss: number; maximumTotalDrawdown: number; dailyLossBreach: boolean; maximumLossBreach: boolean; overall: "PASS" | "FAIL" };
export type SimulationSummary = { simulations: number; step1Pass: number; step1Fail: number; step1PassRate: number; step2ConditionalPass: number; step2ConditionalBase: number; step2ConditionalPassRate: number; fullPass: number; fullFail: number; fullChallengePassRate: number; dailyLossBreaches: number; maximumLossBreaches: number; medianStep1Days: number | null; medianStep2Days: number | null; medianProfitableDays: number | null; worstDailyLoss: number; maximumTotalDrawdown: number; worstFinalBalance: number; medianFinalBalance: number | null; medianNetProfit: number | null };
export const MONEY_EPSILON = 0.01;
export const money = (value: number) => Math.round((value + Number.EPSILON) * 100) / 100;
export function isEligible(summary: Pick<SimulationSummary, "fullChallengePassRate" | "worstDailyLoss" | "maximumTotalDrawdown" | "dailyLossBreaches" | "maximumLossBreaches">) { return summary.fullChallengePassRate >= 95 - MONEY_EPSILON && money(summary.worstDailyLoss) >= -300 - MONEY_EPSILON && money(summary.maximumTotalDrawdown) <= 700 + MONEY_EPSILON && summary.dailyLossBreaches === 0 && summary.maximumLossBreaches === 0; }
const Helsinki = "Europe/Helsinki";
function dayOf(t: BacktestTrade) { const parts = new Intl.DateTimeFormat("en-US", { timeZone: Helsinki, year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(new Date(t.exitTime ?? t.entryTime)); const get = (type: string) => parts.find((x) => x.type === type)?.value ?? "00"; return `${get("year")}-${get("month")}-${get("day")}`; }
function median(values: number[]) { if (!values.length) return null; const a = [...values].sort((x, y) => x - y), m = Math.floor(a.length / 2); return a.length % 2 ? a[m] : (a[m - 1] + a[m]) / 2; }
export function simulateWindow(trades: BacktestTrade[], program: PropFirmProgram, startDate: string): SimulationResult {
  const daily = new Map<string, number>(); for (const t of trades.filter((x) => dayOf(x) >= startDate)) { const d = dayOf(t); daily.set(d, (daily.get(d) ?? 0) + t.netProfit); }
  const days = Array.from(daily.entries()).sort((a, b) => a[0].localeCompare(b[0])); let balance = program.initialBalance, peak = balance, worst = 0, maxDd = 0, step1: "PASS" | "FAIL" = "FAIL", step2: "PASS" | "FAIL" = "FAIL", step1Days: number | null = null, step2Days: number | null = null, profitableDays = 0, stepDays = 0, phase: 1 | 2 = 1, dailyLossBreach = false, maximumLossBreach = false;
  for (const [, pnl] of days) { stepDays++; balance += pnl; peak = Math.max(peak, balance); const dd = Math.max(0, peak - balance); maxDd = Math.max(maxDd, dd); worst = Math.min(worst, pnl); if (pnl <= -program.maxDailyLoss) dailyLossBreach = true; if (program.initialBalance - balance >= program.maxTotalLoss) maximumLossBreach = true; if (pnl >= program.profitableDayMinimum) profitableDays++;
    if (dailyLossBreach || maximumLossBreach) break;
    if (phase === 1 && balance >= program.initialBalance + program.step1Target) { step1 = "PASS"; step1Days = stepDays; balance = program.initialBalance; peak = balance; phase = 2; stepDays = 0; profitableDays = 0; }
    else if (phase === 2 && balance >= program.initialBalance + program.step2Target && profitableDays >= program.minimumProfitableDays) { step2 = "PASS"; step2Days = stepDays; break; }
  }
  return { startDate, step1, step2, step1Days, step2Days, profitableDays, finalBalance: balance, netProfit: balance - program.initialBalance, worstDailyLoss: worst, maximumTotalDrawdown: maxDd, dailyLossBreach, maximumLossBreach, overall: step1 === "PASS" && step2 === "PASS" ? "PASS" : "FAIL" };
}
export function rollingSimulations(trades: BacktestTrade[], program: PropFirmProgram) { return Array.from(new Set(trades.map(dayOf))).sort().map((start) => simulateWindow(trades, program, start)); }
export function aggregateSimulations(results: SimulationResult[]): SimulationSummary { const step1Pass = results.filter((x) => x.step1 === "PASS"), full = results.filter((x) => x.overall === "PASS"); return { simulations: results.length, step1Pass: step1Pass.length, step1Fail: results.length - step1Pass.length, step1PassRate: money(results.length ? step1Pass.length / results.length * 100 : 0), step2ConditionalPass: full.length, step2ConditionalBase: step1Pass.length, step2ConditionalPassRate: money(step1Pass.length ? full.length / step1Pass.length * 100 : 0), fullPass: full.length, fullFail: results.length - full.length, fullChallengePassRate: money(results.length ? full.length / results.length * 100 : 0), dailyLossBreaches: results.filter((x) => x.dailyLossBreach).length, maximumLossBreaches: results.filter((x) => x.maximumLossBreach).length, medianStep1Days: median(step1Pass.flatMap((x) => x.step1Days == null ? [] : [x.step1Days])), medianStep2Days: median(full.flatMap((x) => x.step2Days == null ? [] : [x.step2Days])), medianProfitableDays: median(results.map((x) => x.profitableDays)), worstDailyLoss: money(results.length ? Math.min(...results.map((x) => x.worstDailyLoss)) : 0), maximumTotalDrawdown: money(results.length ? Math.max(...results.map((x) => x.maximumTotalDrawdown)) : 0), worstFinalBalance: money(results.length ? Math.min(...results.map((x) => x.finalBalance)) : 0), medianFinalBalance: median(results.map((x) => x.finalBalance)), medianNetProfit: median(results.map((x) => x.netProfit)) }; }
export const simulatorLimitations = ["Floating intraday loss cannot be calculated when the source contains closed trades only.", "Spread, slippage, commission, and swap follow the source backtest and do not represent the actual The5ers account cost profile."];
export function scaleTrades(trades: BacktestTrade[], selectedLot: number, sourceLot = 0.35) { const factor = selectedLot / sourceLot; return trades.map((t) => ({ ...t, netProfit: t.netProfit * factor, grossProfit: t.grossProfit * factor, commission: t.commission * factor })); }
