import type { Candle } from "@/backtest/types";
import type { LevelType, MarketEvent, SessionName, StructureConfig } from "./types";
export type MarketLevelInput = { levelType: LevelType; price: number; direction: "SUPPORT" | "RESISTANCE"; knownAt?: number; sourceSession?: SessionName | null };
export type MarketEventDiagnostics = { events: MarketEvent[]; duplicateRejected: number; expiredEvents: number; invariantViolations: number; sweepSupport: number; sweepResistance: number; reclaimWithParentSweep: number; failedBreakoutWithParent: number };
type State = { sweep: MarketEvent | null; breakout: MarketEvent | null; sweepOutside: boolean; breakoutOutside: boolean };

export function analyzeMarketEvents(candles: Candle[], levels: MarketLevelInput[], config: StructureConfig, evaluationTime = Number.POSITIVE_INFINITY): MarketEventDiagnostics {
  const events: MarketEvent[] = [], states = new Map<string, State>(), emitted = new Set<string>(); let seq = 0, duplicateRejected = 0, expiredEvents = 0;
  const emit = (event: Omit<MarketEvent, "eventId">) => { const signature = `${event.type}|${event.levelType}|${event.levelPrice}|${event.direction}|${event.sourceCandleTimestamp}`; if (emitted.has(signature)) { duplicateRejected++; return null; } emitted.add(signature); const item = { ...event, eventId: `OFC-${++seq}` }; events.push(item); return item; };
  for (let index = 0; index < candles.length; index++) for (const c of [candles[index]]) for (const l of levels) {
    if (c.timestamp > evaluationTime || c.timestamp < (l.knownAt ?? Number.NEGATIVE_INFINITY)) continue;
    const key = `${l.levelType}:${l.price}:${l.direction}`, support = l.direction === "SUPPORT", state = states.get(key) ?? { sweep: null, breakout: null, sweepOutside: false, breakoutOutside: false }; states.set(key, state);
    const distance = support ? l.price - c.low : c.high - l.price, swept = distance >= config.marketEvents.minimumSweepDistance;
    const expiry = c.timestamp + config.marketEvents.eventExpiryBars * 60_000;
    if (swept && !state.sweepOutside) state.sweep = emit({ parentEventId: null, type: support ? "SUPPORT_SWEEP" : "RESISTANCE_SWEEP", direction: support ? "BULLISH" : "BEARISH", timestamp: c.timestamp, sourceCandleTimestamp: c.timestamp, levelType: l.levelType, levelPrice: l.price, sweepExtreme: support ? c.low : c.high, distance, detectedAt: c.timestamp, confirmationTimestamp: null, knownAt: c.timestamp, expiryTimestamp: expiry, sourceSession: l.sourceSession ?? null, metadata: { candleIndex: index } });
    state.sweepOutside = swept;
    if (state.sweep) { const age = index - Number(state.sweep.metadata.candleIndex); if (age > Math.min(config.marketEvents.maximumReclaimBars, config.marketEvents.eventExpiryBars)) { state.sweep = null; expiredEvents++; } else if (index > Number(state.sweep.metadata.candleIndex) && (support ? c.close >= l.price + config.marketEvents.minimumCloseDistance : c.close <= l.price - config.marketEvents.minimumCloseDistance)) { emit({ parentEventId: state.sweep.eventId, type: support ? "BULLISH_RECLAIM" : "BEARISH_RECLAIM", direction: support ? "BULLISH" : "BEARISH", timestamp: c.timestamp, sourceCandleTimestamp: c.timestamp, levelType: l.levelType, levelPrice: l.price, sweepExtreme: state.sweep.sweepExtreme, distance: Math.abs(c.close - l.price), detectedAt: c.timestamp, confirmationTimestamp: c.timestamp, knownAt: c.timestamp, expiryTimestamp: state.sweep.expiryTimestamp, sourceSession: l.sourceSession ?? null, metadata: {} }); state.sweep = null; } }
    const breakout = support ? c.close < l.price - config.marketEvents.breakoutBuffer : c.close > l.price + config.marketEvents.breakoutBuffer;
    if (breakout && !state.breakoutOutside) state.breakout = emit({ parentEventId: null, type: support ? "BEARISH_BREAKOUT" : "BULLISH_BREAKOUT", direction: support ? "BEARISH" : "BULLISH", timestamp: c.timestamp, sourceCandleTimestamp: c.timestamp, levelType: l.levelType, levelPrice: l.price, sweepExtreme: null, distance: Math.abs(c.close - l.price), detectedAt: c.timestamp, confirmationTimestamp: c.timestamp, knownAt: c.timestamp, expiryTimestamp: expiry, sourceSession: l.sourceSession ?? null, metadata: { candleIndex: index } });
    state.breakoutOutside = breakout;
    if (state.breakout) { const age = index - Number(state.breakout.metadata.candleIndex); if (age > config.marketEvents.eventExpiryBars) { state.breakout = null; expiredEvents++; } else if (index > Number(state.breakout.metadata.candleIndex) && (support ? c.close >= l.price : c.close <= l.price)) { emit({ parentEventId: state.breakout.eventId, type: "FAILED_BREAKOUT", direction: state.breakout.direction, timestamp: c.timestamp, sourceCandleTimestamp: c.timestamp, levelType: l.levelType, levelPrice: l.price, sweepExtreme: null, distance: Math.abs(c.close - l.price), detectedAt: c.timestamp, confirmationTimestamp: c.timestamp, knownAt: c.timestamp, expiryTimestamp: state.breakout.expiryTimestamp, sourceSession: l.sourceSession ?? null, metadata: {} }); state.breakout = null; } }
    const range = c.high - c.low, wick = support ? Math.min(c.open, c.close) - c.low : c.high - Math.max(c.open, c.close);
    if (distance >= 0 && range > 0 && wick / range >= config.marketEvents.rejectionWickRatio && (support ? c.close >= l.price : c.close <= l.price)) emit({ parentEventId: null, type: "REJECTION", direction: support ? "BULLISH" : "BEARISH", timestamp: c.timestamp, sourceCandleTimestamp: c.timestamp, levelType: l.levelType, levelPrice: l.price, sweepExtreme: support ? c.low : c.high, distance: Math.max(0, distance), detectedAt: c.timestamp, confirmationTimestamp: c.timestamp, knownAt: c.timestamp, expiryTimestamp: expiry, sourceSession: l.sourceSession ?? null, metadata: { wickRatio: wick / range } });
  }
  const ids = new Set(events.map((x) => x.eventId)), reclaims = events.filter((x) => x.type.endsWith("RECLAIM")), failed = events.filter((x) => x.type === "FAILED_BREAKOUT");
  const invariantViolations = reclaims.filter((x) => !x.parentEventId || !ids.has(x.parentEventId)).length + failed.filter((x) => !x.parentEventId || !ids.has(x.parentEventId)).length + events.filter((x) => x.knownAt > evaluationTime).length;
  return { events, duplicateRejected, expiredEvents, invariantViolations, sweepSupport: events.filter((x) => x.type === "SUPPORT_SWEEP").length, sweepResistance: events.filter((x) => x.type === "RESISTANCE_SWEEP").length, reclaimWithParentSweep: reclaims.filter((x) => x.parentEventId).length, failedBreakoutWithParent: failed.filter((x) => x.parentEventId).length };
}
export function detectMarketEvents(candles: Candle[], levels: MarketLevelInput[], config: StructureConfig, evaluationTime?: number): MarketEvent[] { return analyzeMarketEvents(candles, levels, config, evaluationTime).events; }
