import { randomUUID, createHash } from "node:crypto";
import { NextResponse } from "next/server";
import { getMongoDb } from "@/lib/mongodb";
import { SAVED_METHODS } from "@/config/saved-methods";
import { PROP_FIRM_PROGRAMS } from "@/config/prop-firm-programs";
import { aggregateSimulations, rollingSimulations, scaleTrades, simulatorLimitations } from "@/lib/prop-firm-simulator";
import { normalizeHistoryRecord, recommendationForHistory } from "@/lib/prop-firm-simulator/format";
import { simulationHistoryFilter } from "@/lib/prop-firm-simulator/history";
export const dynamic = "force-dynamic";
const collection = "prop_firm_simulations";
function valid(body: Record<string, unknown>) { const lot = Number(body.lot), start = String(body.startDate), end = String(body.endDate); return lot > 0 && /^\d{4}-\d{2}-\d{2}$/.test(start) && /^\d{4}-\d{2}-\d{2}$/.test(end) && start >= "2022-01-03" && end <= "2026-06-16" && start <= end; }
export async function POST(request: Request) { try { const body = await request.json() as Record<string, unknown>; if (!valid(body)) return NextResponse.json({ error: "Periode atau lot tidak valid." }, { status: 400 }); const method = SAVED_METHODS.find((x) => x.id === body.methodId) ?? SAVED_METHODS[0], program = PROP_FIRM_PROGRAMS[0], lot = Number(body.lot), startDate = String(body.startDate), endDate = String(body.endDate), db = await getMongoDb(); const source = await db.collection("backtest_trades").find({ runId: method.sourceRunId }).sort({ entryTime: 1 }).toArray(), filtered = source.filter((x) => String(x.exitTime ?? x.entryTime) >= `${startDate}T00:00:00.000Z` && String(x.exitTime ?? x.entryTime) <= `${endDate}T23:59:59.999Z`), simulations = rollingSimulations(scaleTrades(filtered as never, lot), program), summary = aggregateSimulations(simulations), fingerprint = createHash("sha256").update(JSON.stringify({ methodId: method.id, startDate, endDate, lot, program: program.id, simulatorVersion: "1.1.0" })).digest("hex"), existing = await db.collection(collection).findOne({ fingerprint }); if (existing) return NextResponse.json({ simulationId: existing.simulationId, saved: true, duplicate: true, method, selected: { startDate, endDate, lot }, summary: normalizeHistoryRecord(existing as Record<string, unknown>), limitations: simulatorLimitations }); const recommendation = recommendationForHistory({ ...summary, maximumDrawdown: summary.maximumTotalDrawdown }); const simulationId = `pfs-${randomUUID()}`, document = { simulationId, createdAt: new Date(), fingerprint, methodId: method.id, methodName: method.name, sourceRunId: method.sourceRunId, startDate, endDate, selectedLot: lot, propFirmProgramId: program.id, propFirmProgramName: program.name, ...summary, maximumDrawdown: summary.maximumTotalDrawdown, recommendationStatus: recommendation.recommendationStatus, recommendationReason: recommendation.recommendationReason, dailyLossBuffer: 500 + summary.worstDailyLoss, totalLossBuffer: 1000 - summary.maximumTotalDrawdown, limitations: simulatorLimitations, simulatorVersion: "1.1.0" }; await db.collection(collection).insertOne(document); return NextResponse.json({ simulationId, saved: true, duplicate: false, method, selected: { startDate, endDate, lot }, summary: document, limitations: simulatorLimitations }); } catch (error) { return NextResponse.json({ error: error instanceof Error && /timeout|Mongo/i.test(error.message) ? "MongoDB timeout saat menyimpan simulasi." : "Simulator gagal dijalankan." }, { status: 500 }); } }
export async function GET() { try { const docs = await (await getMongoDb()).collection(collection).find(simulationHistoryFilter, { projection: { _id: 0 } }).sort({ createdAt: -1 }).toArray(); return NextResponse.json({ history: docs.map((x) => normalizeHistoryRecord(x as Record<string, unknown>)) }); } catch { return NextResponse.json({ error: "Tidak dapat memuat Simulation History." }, { status: 500 }); } }
